### ISSUE TITLE
Bug in the calculation of inchikey while getting MassBank entry.

### ISSUE THREAD

**Issue by adelabriere** [pkrog/biodb#150]
Infinite recursion sometimes occurs when calling `entry <-
 getEntry("massbank.jp",some_mass_bank_id,drop=TRUE)` 
 and when the inchi key is then computed after calling  `entry$getFieldValue("inchikey")`. However it seems quite random and not really dependent of the massbank ID. 

I had this bug when calling for more than 100 massbank entries

If I manage to build a reproducible example I will put it online.

The reccuring message look like this :

> INFO[2018-01-17 09:52:40][BiodbFactory::.createNewEntries()] : Creating 1 entries from ids 48300 ...
> INFO[2018-01-17 09:52:40][BiodbFactory::getEntryContent()] : Get chebi entry content(s) for 1 id(s)...
> INFO[2018-01-17 09:52:40][BiodbFactory::getEntryContent()] : 0 chebi entry content(s) loaded from cache.
> INFO[2018-01-17 09:52:40][BiodbFactory::getEntryContent()] : 1 entry content(s) need to be fetched from chebi database

... repeated infinitely. It occurs when using it in a `sapply` function

**Comment by pkrog** [comment]
Hi Alexis, yes please try to give a code for reproducing it. I'll try to debug it asap.
