### ISSUE TITLE
Can it get SMILES from database ?

### ISSUE THREAD

**Issue by hcji** [pkrog/biodb#213]
Hi, 
Nice work! I wonder can this package obtain SMILES, which indicates the structures of the compounds, from database ?

Thank you

**Comment by pkrog** [comment]
Hi,

Yes it can. For example it works for ChEBI, ChemSpider, HMBD Metabolites in which you access it through the field "smile". For NcbiPubchemComp, on the other hand you get two fields: "smiles.canonical" and "smiles.isomeric".

Here is an example of code:
```r
mybiodb <- biodb::Biodb()
entry <- mybiodb$getFactory()$getEntry('chebi', '2528')
entry$getFieldValue('smiles')
```

Pierrick

**Comment by hcji** [comment]
Thanks for your help.
